# Generated by Django 4.0.7 on 2022-09-18 16:53

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='title'),
        ),
    ]
