# Generated by Django 4.0.7 on 2022-09-30 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_blog_user_verifyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
